remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [SUMNEET KHANNA, CAPM]
DESCRIPTION: [Senior Analyst, Data Analytics - American Express] 
